version: "3"
services:
  localstack:
    image: localstack/localstack:0.12.8
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - SERVICES=lambda,s3,cloudwatch-logs
  tests:
    build:
      context: .
      dockerfile: test.dockerfile
    depends_on:
      - localstack